<?php


namespace api\modules\v1\controllers;

use frontend\models\Manufacturer;
use yii;
use yii\base\Controller;

class FilterController extends Controller
{

    public function init()
    {
        \Yii::$app->language = \Yii::$app->request->get('lang');
        \Yii::$app->response->format = 'json';

        parent::init(); // TODO: Change the autogenerated stub

    }

    public function actionManufacturers()
    {
        $manufacturers = Manufacturer::find()->all();
        return $manufacturers;
    }


}